version: "3.8"

services:
  client:
    build: client
    ports:
      - "5173:5173"
    networks:
      - mern
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build: server
    ports:
      - "8747:8747"
    networks:
      - mern
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules

  mongodb:
    build: db
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local